### ISSUE TITLE
Store ENVKEY on server

### ISSUE THREAD

**Issue by manuelmeurer** [envkey/envkey-ruby#1]
Hi there,

I'm just setting up EnvKey for my Rails app.
For storing the ENVKEY on my production server, would a suitable approach be to create a `.env` file during deploy? Of course my local `.env` file is gitignored and contains the development ENVKEY, but since I have a custom deploy script (using Ansible), I could easily create a `.env` file on the server as well containing the production ENVKEY.
What would be the disadvantage to setting it as a proper environment variable on the server, if any?
Thanks! EnvKey is awesome! 😄

**Comment by danenania** [comment]
Hi @manuelmeurer, yes that will work just fine. The gem first checks for an `ENVKEY` environment variable, then a `.env` file regardless of whether you're in dev/production.

The reason that an `ENVKEY` environment variable is recommended over a `.env` file in production is that there's less that can go wrong in terms of managing access. If you have it in a deploy script, for example, that's stored in a Github repo (even if it's a separate repo from your app's main codebase), you've 1) given a third party (Github) unnecessary access to your secrets and 2) have to manage access to secrets in two places now--EnvKey and your Ansible repo--so there's more potential to accidentally give someone access to production secrets who doesn't need it. 

With the environment variable approach, you can couple access to production secrets directly to production server access. But if you're able to address the issues I mentioned and a `.env` file is simpler for you, then that works!

**Comment by manuelmeurer** [comment]
Great, thanks for the explanation!
One thing I forgot to mention is that I'm running several Rails apps on the same server, under the same user. Since each app would need a separate ENVKEY, setting an env var will not work, right?

**Comment by danenania** [comment]
Yeah, in that case you could either need to use the `.env` file approach as you mentioned (and be careful about access control), or do a little glue scripting to supply each app with the right `ENVKEY`. You could do that for example by setting an environment variable for each app:
```
APP_1_ENVKEY=...
APP_2_ENVKEY=...
```

And then convert each one back to an `ENVKEY` when you start the process:
```
$ cd ~/app1
$ ENVKEY=$APP_1_ENVKEY && puma
$ cd ~/app2
$ ENVKEY=$APP_2_ENVKEY && puma
```

**Comment by manuelmeurer** [comment]
Thanks again!
I think I'll go with the `.env` file approach for now since I already copy a few other confidential files to the server on deploy.
