### ISSUE TITLE
Custom environments

### ISSUE THREAD

**Issue by manuelmeurer** [envkey/envkey-ruby#2]
Why can't I create additional environments, or at least rename existing ones? I don't need "staging" for example, but "CI".

**Comment by manuelmeurer** [comment]
Ah, just noticed you can create an env key for a test server, connected to the dev environment. That'll work! :)
Still, don't you think creating more/custom environments would be useful?

**Comment by danenania** [comment]
Hi @manuelmeurer, in the latest version of the app (currently v1.1.2), you can create additional custom environments as 'sub-environments' that add or override variables on top of development, staging, or production. 

To trigger auto-update, open the app then restart after a minute or so (you may also be prompted to restart). You can confirm the version number at the bottom left corner of the sidebar after logging in.

Updates to the site/docs describing this feature will be added soon. For now, here are a few screenshots illustrating how it works:

![1-sub-envs](https://user-images.githubusercontent.com/545350/32521912-4473ec20-c3e3-11e7-9ba6-2adbd7eee572.png)

![screen shot 2017-10-30 at 1 44 39 pm](https://user-images.githubusercontent.com/545350/32521926-4cb69194-c3e3-11e7-83db-b6783240f82e.png)

![screen shot 2017-10-30 at 1 45 08 pm](https://user-images.githubusercontent.com/545350/32521930-4fdcbff6-c3e3-11e7-8198-d3df036220d2.png)

**Comment by manuelmeurer** [comment]
Thanks! Do you have an example of when I would need a sub-environment?

Until now I had a separate settings/secrets file ([I created my own solution some years ago](https://github.com/krautcomputing/nifty_settings)) for CI with only dummy values, since I didn't want the CI server to have my "real" settings file because it includes the production settings as well, but I couldn't NOT have a settings file on CI because the app expects some of them to always exist.
But now with EnvKey this is not necessary anymore, I created a test env key, added it to my CI config (I use Codeship) and it has access to only the development settings. Problem solved! 😃

**Comment by danenania** [comment]
Great! Making CI easier to manage is definitely one of the goals. 

For sub-environments, imagine you have a demo version that uses production config except it connects to a different database, or a worker process that needs some extra configuration, or some different settings when you run on CI vs. development. They are for any situation where you need to go beyond the basic development/staging/production split. But that said, if you don't really need them, it's definitely better to keep things simple!

**Comment by manuelmeurer** [comment]
👍  Makes sense! I'll close this for now.
Hope you don't mind me opening issues for questions like these! 😄

**Comment by danenania** [comment]
@manuelmeurer Not at all!
