### ISSUE TITLE
envkey 1.2.0 causes infinite IPv6 loopback lookup when off network.

### ISSUE THREAD

**Issue by j05h** [envkey/envkey-ruby#4]
When upgrading to envkey 1.2.0 we noticed that our clients would hang if off network. This would also happen with certain VPN configurations. Reverting our application to use 1.1.0 resolved the issue.

Running:

`$ strace -f -e trace=network -s 10000 rake -T` 

would eventually lead to the following:

`[pid 19406] getpeername(6,  <unfinished ...>
[pid 19408] setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [0], 4 <unfinished ...>
[pid 19406] <... getpeername resumed> {sa_family=AF_INET6, sin6_port=htons(53), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [112->28]) = 0
[pid 19408] <... setsockopt resumed> )  = 0
[pid 19408] setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
[pid 19408] connect(3, {sa_family=AF_INET6, sin6_port=htons(53), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
[pid 19408] getsockname(3, {sa_family=AF_INET6, sin6_port=htons(39363), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [112->28]) = 0
[pid 19408] getpeername(3, {sa_family=AF_INET6, sin6_port=htons(53), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [112->28]) = 0
[pid 19406] socket(AF_INET6, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 3
[pid 19406] setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
[pid 19406] setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
[pid 19406] connect(3, {sa_family=AF_INET6, sin6_port=htons(53), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, 28) = 0
[pid 19406] getsockname(3, {sa_family=AF_INET6, sin6_port=htons(53694), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [112->28]) = 0
[pid 19406] getpeername(3, {sa_family=AF_INET6, sin6_port=htons(53), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=htonl(0), sin6_scope_id=0}, [112->28]) = 0
`

Note at the end, it seems to be looking for the `::1` loopback. We've replicated this with MacOS and Ubuntu. Network on, no VPN, the code works reliably, but without network or on VPN, it will hang indefinitely.

**Comment by danenania** [comment]
@j05h Thanks for the detailed bug report - this is an issue with the latest envkey-fetch release not properly responding to a network error. A new release will be out shortly.
