### ISSUE TITLE
Use git tags and create releases

### ISSUE THREAD

**Issue by manuelmeurer** [envkey/envkey-ruby#7]
Could you please tag each released version and [create a release on GitHub](https://help.github.com/en/articles/creating-releases)?
This makes it easier to compare versions for example and keep up with the latest releases.
I use [gem-release](https://github.com/svenfuchs/gem-release) to automatically bump the version and push a release to Rubygems, but I don't think it creates a release on GitHub as well.

**Comment by danenania** [comment]
Yes, good idea—we’ll do this in the future. Thanks!

**Comment by danenania** [comment]
We're doing a better job of this in v2, which has just launched:. Each sdk release (including ruby) is tagged in the new v2 repo: https://github.com/envkey/envkey
