### ISSUE TITLE
Secrets not updating on redeploy

### ISSUE THREAD

**Issue by larryrutledge** [envkey/envkey-ruby#8]
Having an issue where my secrets are not being reloaded when deploying a new build of my application (Note: app is deployed in Cloud 66 in a Kubernetes container).

If I log into the new build and launch the Rails console it does return the new secret value, but the application still returns the first value ever assigned in the EnvKey app, regardless of how many times its been changed or the app has been deployed/launched.

Based on Issue #5 I changed my Gemfile to 1.2.6 but still the new deploy returns the original env variable value.

**Comment by danenania** [comment]
Hi! 

First of all, if you install and run [envkey-fetch](https://github.com/envkey/envkey-fetch) with the same `ENVKEY` are you getting the latest values in the json output?

Assuming you are, could you describe what happens when a new build gets deployed? Which web server are you using--unicorn? Is each build deployed into fresh kubernetes pods or are you updating in place somehow? A common cause of issues like this is that the environment variables are already set somehow prior to `envkey` running, and envkey then defers to the existing environment vars.

**Comment by larryrutledge** [comment]
Hi!

Ok I installed envkey-fetch and ran using my `ENVKEY` value. I got the current values stored in ENVKEY. I then launched the ENVKEY app and changed the variable of interest then re-ran `envkey-fetch` and the resulting json output showed the new value - the behavior I would expect.

We are using unicorn.  I am following up with Cloud66 to get the answer to the other questions. I know they deploy using Kubernetes, but not sure the exact build/rebuild process.

The only thing that is confusing is if I launch the rails console and check the envkey value I'm interested in I get the new value. But the new rails app build still has the original value for that key. None of the secrets of interest are stored in OS environment variables. They are all stored only `envkey`

**Comment by danenania** [comment]
Interesting... it's definitely strange that you'd be getting the latest values in the console, but not the app process. It sounds like the app process is not fully restarting on updates.

If you paste in your dockerfile I can see whether I can reproduce it locally.

Something else to try could be using [envkey-source](https://github.com/envkey/envkey-source) via your dockerfile. Since it works on the shell level it is often more resistant to process-oriented glitches like this than the language-specific libs.

**Comment by larryrutledge** [comment]
So it turns out I was incorrect and they are not using Kubernetes. They have a Rails product using the unicorn web server. The default shutdown sequence is sent the USR2 signal.

Because the process is forked (which carries over the environment variables) is why they recommended issue #5 here. But unfortunately upgrading the gem to 1.2.6 didn't make a difference. Do I need to perform anything during the `after_fork` to make it refresh the values?

**Comment by larryrutledge** [comment]
In `unicorn.rb` I put the following:
```
  Rails.logger.info "***** AFTER FORK"
  Rails.logger.info "***** RAILS __ENVKEY_VARS (before): #{ENV["__ENVKEY_VARS"]}"
  Rails.logger.info "***** ENVKEY::CORE.LOAD_ENV"
  Envkey::Core.load_env
  Rails.logger.info "***** RAILS __ENVKEY_VARS (after): #{ENV["__ENVKEY_VARS"]}"
```
After deploy I checked the log and see the following:
```
INFO -- : ***** AFTER FORK
INFO -- : ***** RAILS __ENVKEY_VARS (before): []
INFO -- : ***** ENVKEY::CORE.LOAD_ENV
INFO -- : ***** RAILS __ENVKEY_VARS (after): []
```

If I load the console and view `ENV["__ENVKEY_VARS"]` I see all the envkey variable names, which I expect. But looking at the log of the server deploy its empty every time.

I also added the following into `after_fork` to see what fetch is returning:
`res = Envkey::Fetch.fetch_env(ENV["ENVKEY"])`

and when I examine `res` I see all the values I expect from envkey with the current values. But they are never being assigned.

Writing this out I think I figured out what is happening.
Because `ENV["__ENVKEY_VARS"]` is empty coming into `load_env` no existing values are going to be overwritten if they exist. And because the fork maintains existing environment all those existing keys already exist.
This means that after the `fetch` when it checks to see if the value does *not* exist or is in the overwrite array, neither condition is true so it does not overwrite the value and does not add the variable to the overwrite array (`ENV["__ENVKEY_VARS"]`)

I suspect that `ENV["__ENVKEY_VARS"]` is something that was added in a newer version (possibly in 1.2.6) which means the version we were running before never populated this array. Because the fork doesn't clear the existing environment when this was added via the updated gem it never got populated because the variables already existed in the environment.

To confirm this I added a new variable to `envkey` and checked the `ENV["__ENVKEY_VARS"]` after redeploy and it now contains just that one new variable.

The current solution being tested is to hard code all the existing keys into `ENV["__ENVKEY_VARS"]` so they are picked up as values to overwrite (coming from `envkey`). And after deploy remove the line to hard code them as they'll be set going forward - and any hard server restarts the environment would be cleared anyway so they would be picked up to change.

What would be ideal is to add a reload option to `load_env` so it would overwrite even if the key already exists in the environment.

Hopefully this is clear. Please let me know if you see any issues with my analysis and/or solution. Or if you have any other thoughts/ideas.

Thanks

**Comment by larryrutledge** [comment]
I have confirmed this works. It would be nice if there was a reload option in `load_env` to overwrite all the values. But the hard coding solution resolved it for us.

**Comment by danenania** [comment]
@larryrutledge Thanks for the detailed explanation--I agree a force overwrite option for `load_env` is a good idea.
